name: fcode_pos
description: "FCODE Pos - A starter kit for building Flutter applications with Appwrite backend services."
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.8.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  url_launcher: ^6.3.1
  window_manager: ^0.5.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.1.0
  flutter_launcher_icons: ^0.14.4
  http: ^1.5.0
  path_provider: ^2.1.5
  web: ^1.1.1
  cookie_jar: ^4.0.8
  package_info_plus: ^9.0.0
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_riverpod: ^3.0.3
  currency_text_input_formatter: ^2.3.0
  # passkeys: ^2.1.0
  pretty_dio_logger: ^1.4.0
  image_gallery_saver: ^2.0.3
  flutter_html: ^3.0.0
  share_plus: ^12.0.1


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/
  
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
        - asset: assets/fonts/GoogleSans-Bold.ttf
    - family: MomoTrustSans
      fonts:
        - asset: assets/fonts/momo/MomoTrustSans-Regular.ttf
        - asset: assets/fonts/momo/MomoTrustSans-Light.ttf
          weight: 300
        - asset: assets/fonts/momo/MomoTrustSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/momo/MomoTrustSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/momo/MomoTrustSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/momo/MomoTrustSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/momo/MomoTrustSans-ExtraBold.ttf
          weight: 800
      
